### ISSUE TITLE
Versioning Issues

### ISSUE THREAD

**Issue by rockchalkwushock** [audinue/rollup-plugin-multidest#3]
There are some problems with the versioning and distribution of this package:

```plaintext
npm: 1.0.0
current package.json on Github: 1.0.1
```

The following conflict is caught by [bithound](https://www.bithound.io/github/rockchalkwushock/how-to-open-source/36e1f993d06045a0d84d7078f471dde1504fd108/dependencies/npm/rollup-plugin-multidest)

Further more when doing a `yarn add -D rollup-plugin-multidest` when traveling to `/node_modules/rollup-plugin-multidest/package.json` none of the project dependencies are listed this causes errors in the build process because `deepmerge is not being found` yet **is** a dependency for this package to work properly.

I believe if the project is rebuilt, redistributed to npm, & versioned correctly these errors will be resolved.

**Comment by audinue** [comment]
Please read #2 

Thank you.

**Comment by rockchalkwushock** [comment]
I see. So is this package going to be deprecated then as this would be the best practice since it's provided by rollup internally?

**Comment by audinue** [comment]
It *was* deprecated :)

![screenshot_1](https://cloud.githubusercontent.com/assets/1407800/26053112/c04cb62e-3991-11e7-88b1-cbd5ae971463.jpg)

**Comment by rockchalkwushock** [comment]
I see thank you. Closing.

**Comment by tunnckoCore** [comment]
@audinue probably it need better message with `deprecated` keyword included and pointing to Rollup docs. Because this _"Use 'targets' in rollup config"_ won't help for some like you. :)
